package net.createmod.ponder.foundation.ui;

enum SymbolicColor {
    CHROME_GLOW,
    CHROME_BORDER_TOP,
    CHROME_BORDER_BOTTOM,
    CHROME_BORDER_SIDE,
    CHROME_VIGNETTE,
    HEADER_FILL,
    HEADER_RIGHT_EDGE,
    HEADER_UNDERLINE,
    HEADER_SLOT_OUTER,
    HEADER_SLOT_INNER,
    HEADER_EYEBROW,
    HEADER_TITLE,
    HEADER_SUBTITLE,
    HEADER_INDEX,
    GROUP_CHIP_FILL,
    GROUP_CHIP_BORDER,
    GROUP_CHIP_TEXT
}
