package net.createmod.ponder.foundation.ui;

enum ThemeMetric {
    CHROME_GLOW_INSET,
    CHROME_GLOW_BOTTOM_INSET,
    CHROME_TOP_GLOW_HEIGHT,
    CHROME_BOTTOM_GLOW_HEIGHT,
    CHROME_GLOW_ALPHA_SCALE,
    CHROME_BORDER_ALPHA_SCALE,
    CHROME_VIGNETTE_ALPHA_SCALE,
    CHROME_LOGO_ALPHA_SCALE,
    HEADER_MAX_WIDTH,
    HEADER_HEIGHT,
    HEADER_ALPHA_SCALE,
    HEADER_UNDERLINE_ALPHA_SCALE,
    HEADER_SLOT_OUTER_ALPHA_SCALE,
    HEADER_SLOT_INNER_ALPHA_SCALE,
    GROUP_CHIP_FILL_ALPHA_SCALE,
    GROUP_CHIP_BORDER_ALPHA_SCALE
}
